"""add allocation_simulations table

Revision ID: 19b5e158d9a6
Revises: 07cc2718e242
Create Date: 2026-08-10 19:04:06.555084
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b5e158d9a6'
down_revision: Union[str, Sequence[str], None] = '07cc2718e242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('methode', sa.String(length=10), nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('part_croissance', sa.Float(), nullable=False),
    sa.Column('part_defensive', sa.Float(), nullable=False),
    sa.Column('rendement_annuel_espere', sa.Float(), nullable=False),
    sa.Column('volatilite_annuelle_estimee', sa.Float(), nullable=False),
    sa.Column('ratio_sharpe_estime', sa.Float(), nullable=False),
    sa.Column('source_donnees', sa.String(length=60), nullable=False),
    sa.Column('allocation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allocation_simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_simulations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_simulations_user_id'))

    op.drop_table('allocation_simulations')
    # ### end Alembic commands ###
