"""add savings_goals table and link to allocation_simulations

Revision ID: f9f132d5b194
Revises: 19b5e158d9a6
Create Date: 2026-08-10 19:25:30.438233
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f132d5b194'
down_revision: Union[str, Sequence[str], None] = '19b5e158d9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=120), nullable=False),
    sa.Column('montant_cible', sa.Float(), nullable=False),
    sa.Column('montant_actuel', sa.Float(), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_goals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('allocation_simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_allocation_simulations_goal_id'), ['goal_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_allocation_simulations_goal_id_savings_goals",
            "savings_goals", ["goal_id"], ["id"], ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allocation_simulations', schema=None) as batch_op:
        batch_op.drop_constraint("fk_allocation_simulations_goal_id_savings_goals", type_="foreignkey")
        batch_op.drop_index(batch_op.f('ix_allocation_simulations_goal_id'))
        batch_op.drop_column('goal_id')

    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_goals_user_id'))

    op.drop_table('savings_goals')
    # ### end Alembic commands ###
